# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b78e756e0641a727f999ab2d3480442e562e4f5dca82f5a4d61f7af6fb9c83199c5721ca54f27b30bf557060834c766e5297f5b5dabae09406e21da23ea379b

test:
  secret_key_base: f3d00fc2dab3960231d2445fa0c94ae295db2e9a9b8f64209781e9157e8766f46037e65bf46ade0c9901af082aa9ce623b538700406330fa8814df17d305263a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
